[package]
name = "rustypy-multi-flct"
version = "0.1.0"
edition = "2024"

[lib]
name = "rustypy_multi_flct"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
ndarray = "0.15"
rust-core = { path = "../../rust-core" }